apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-rs-app 
  template: 
    metadata:
      labels:
        app: nginx-rs-app 
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2 
          ports:
            - containerPort: 80
